config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, 
             controllers: { sessions: 'sessions' },
             path: 'gurus', 
             path_names: { sign_in: :login, sign_out: :logout }

  root 'tests#index'

  resources :tests, only: :index do 
    member do 
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
  end

  get 'feedbacks', to: 'feedback#new'
  post 'feedbacks', to: 'feedback#create' 

  # get "users", to: "users#show"
  get 'badges', to: 'user_badges#index'


end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_number_of_answers, on: :create

  private
  def validate_number_of_answers
    error.add(:question) if question.answers.count > 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord

  RULES = %w[success_category success_on_first_try success_all_level].freeze
  
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image, :rule, presence: true
  validates :rule, inclusion: { in: RULES }
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord

	belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
  
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: "User"

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  scope :easy, -> { where(level: 0..2) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :level, -> level { where(level: level) }
  scope :by_category, -> name { joins(:category).where(categories: {title: name}) }

  scope :passed, ->(user) { joins(:test_passages).
    where(test_passages: { passed: true, user: user })}

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def self.names_by_category(name)
    joins("JOIN categories ON categories.id = tests.category_id")
    .where(categories: {title: name}).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: "Question", optional: true

  before_validation :before_validation_set_first_question, on: :create

  # scope :passed, -> { where("result >= 85 ")}

  POINTS_TO_COMPLETE = 85

  def completed?
    current_question.nil?
  end

  def empty_answers?(answer_ids)
    answer_ids.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    self.current_question = next_question
    save!
  end

  def score
    correct_questions * 100 / test.questions.count
  end

  def passed
    score >= POINTS_TO_COMPLETE
  end

  def passed?
    score >= POINTS_TO_COMPLETE
  end

  def question_index
    test.questions.index(current_question) + 1
  end

  def time_passed
    Time.now - created_at
  end

  def time_left(test_passage)
    test_passage.test.duration - (Time.now - test_passage.created_at).to_i if test_passage.test.duration > 0
  end

  private
  def before_validation_set_first_question
    self.current_question = test.questions.first
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
     correct_answers_count == answer_ids.count 
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
  
end

app/models/test_past.rb
class TestPast < ApplicationRecord
  belongs_to :test
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  
  has_many :own_tests, class_name: "Test", foreign_key: :author_id, dependent: :nullify
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  
  def test_by_level(level)
    tests.level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id) 
  end
  
  def admin?
    self.is_a?(Admin)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :badge
  belongs_to :user

  scope :assigned_badges, -> (user, badge) { where(user: user, badge: badge) }
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to [:admin, @badge], notice: "Excelent"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge]
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private
  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :image, :rule, :parameter)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  NOTICE_KEYS = {
    alert: "alert alert-danger", notice: "alert alert-info", success: "alert alert-success",
    warning: "alert alert-warning", primary: "alert alert-primary"
  }

  def current_year
    Date.current.strftime('%Y')
  end

  def github_url(author, repo)
    link_to 'Test-Guru', "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def class_message(key)
    NOTICE_KEYS[key.to_sym]
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/user_badges_helper.rb
module UserBadgesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.name %></td>
  <td class="align-middle">
    <%= image_tag(badge.image, size: 100) %>
  </td>
  <td class="align-middle"><%= badge.rule %></td>
  <td class="align-middle"><%= badge.parameter %></td>
  <td class="align-middle"><%= link_to t('admin.answers.answer.show'), admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to t('admin.answers.answer.edit'), edit_admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to t('admin.answers.answer.delete'), admin_badge_path(badge),
                                       method: :delete,
                                       data: { confirm: t('admin.answers.answer.del_confirm') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form|%>
  <%= render "shared/errors", resource: @badge %>

  <div class="form-group col-5">
    <p>
      <%= form.label :rule %>
       <%= form.select(:rule, [[t('.success_category'), Badge::RULES[0]],
                              [t('.first_try'), Badge::RULES[1]],
                              [t('.all_level'), Badge::RULES[2]]],
                      prompt: t('.prompt'), class: "form-select") %>
    </p>

    <p>
      <%= form.label :image %>
      <%= form.text_field :image, class: "form-control" %>
    </p>

    <p>
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </p>

     <p>
      <%= form.label :parameter %>
      <%= form.text_field :parameter, class: "form-control" %>
    </p>

    <p><%= form.submit class: "btn btn-primary" %></p>

 </div>

<% end %>

app/views/admin/badges/edit.html.erb
<h1>Edit badge</h1>
<%= render "form" %>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4"><h1><%= t('.header') %></h1></div>

  <div class="col-12"><%= link_to t('.new_badge'), new_admin_badge_path %>
    <%= render 'shared/errors', resource: @badge %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= t('.name') %></th>
        <th><%= t('.image') %></th>
        <th><%= t('.rule') %></th>
        <th><%= t('.parameter') %></th>
        <th colspan="3"><%= t('tests.index.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <%= render @badges %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/badges/new.html.erb
<h1>Create new Badge</h1>
<%= render "form" %>

app/views/admin/badges/show.html.erb
<p>
  <strong><%= t('admin.badges.index.name') %></strong>
  <%= @badge.name %>
</p>

<p>
  <%= image_tag @badge.image, :alt => "image", size: 100 %>
</p>

<p>
  <strong><%= t('admin.badges.index.rule') %></strong>
  <%= @badge.rule %>
</p>
<br>

<%= link_to t('admin.badges.edit.edit_title'), edit_admin_badge_path(@badge) %> |
<%= link_to t('admin.answers.edit.back'), admin_badges_path %>