config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, 
             controllers: { sessions: 'sessions' },
             path: 'gurus', 
             path_names: { sign_in: :login, sign_out: :logout }

  root 'tests#index'

  resources :tests, only: :index do 
    member do 
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
  end

  get 'feedbacks', to: 'feedback#new'
  post 'feedbacks', to: 'feedback#create' 

  # get "users", to: "users#show"
  get 'badges', to: 'user_badges#index'


end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_number_of_answers, on: :create

  private
  def validate_number_of_answers
    error.add(:question) if question.answers.count > 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord

  RULES = %w[success_category success_on_first_try success_all_level].freeze
  
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image, :rule, presence: true
  validates :rule, inclusion: { in: RULES }
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord

	belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
  
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: "User"

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  scope :easy, -> { where(level: 0..2) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :level, -> level { where(level: level) }
  scope :by_category, -> name { joins(:category).where(categories: {title: name}) }

  scope :passed, ->(user) { joins(:test_passages).
    where(test_passages: { passed: true, user: user })}

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def self.names_by_category(name)
    joins("JOIN categories ON categories.id = tests.category_id")
    .where(categories: {title: name}).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: "Question", optional: true

  before_validation :before_validation_set_first_question, on: :create

  # scope :passed, -> { where("result >= 85 ")}

  POINTS_TO_COMPLETE = 85

  def completed?
    current_question.nil?
  end

  def empty_answers?(answer_ids)
    answer_ids.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    self.current_question = next_question
    save!
  end

  def score
    correct_questions * 100 / test.questions.count
  end

  def passed
    score >= POINTS_TO_COMPLETE
  end

  def passed?
    score >= POINTS_TO_COMPLETE
  end

  def question_index
    test.questions.index(current_question) + 1
  end

  def time_passed
    Time.now - created_at
  end

  def time_left(test_passage)
    test_passage.test.duration - (Time.now - test_passage.created_at).to_i if test_passage.test.duration > 0
  end

  private
  def before_validation_set_first_question
    self.current_question = test.questions.first
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
     correct_answers_count == answer_ids.count 
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
  
end

app/models/test_past.rb
class TestPast < ApplicationRecord
  belongs_to :test
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  
  has_many :own_tests, class_name: "Test", foreign_key: :author_id, dependent: :nullify
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges
  
  def test_by_level(level)
    tests.level(level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id) 
  end
  
  def admin?
    self.is_a?(Admin)
  end

  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :badge
  belongs_to :user

  scope :assigned_badges, -> (user, badge) { where(user: user, badge: badge) }
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  NOTICE_KEYS = {
    alert: "alert alert-danger", notice: "alert alert-info", success: "alert alert-success",
    warning: "alert alert-warning", primary: "alert alert-primary"
  }

  def current_year
    Date.current.strftime('%Y')
  end

  def github_url(author, repo)
    link_to 'Test-Guru', "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def class_message(key)
    NOTICE_KEYS[key.to_sym]
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-dark bg-primary p-3">
  <%= link_to t('.header'), admin_tests_path, class: "navbar-brand btn btn-dark" %>

  <span class="navbar-text">
    <%= t('header.welcome') %>, <b><%= current_user.email %></b> |
    <%= link_to t('header.logout'), destroy_user_session_path, method: :delete %>
  </span>
</nav>

<ul class="nav text-light bg-dark p-1">
  <li class="nav-item">
    <%= link_to t(".new_badge"), new_admin_badge_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(".badges"), admin_badges_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t('.gists'), admin_gists_path, class: "nav-link" %>
  </li>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>
    <%= render 'shared/flash' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width-device-width, initial-scale=1, shrink-to-fit=no">
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/header'%>
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'shared/footer'%>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource&.errors.present? %>
  <%= content_tag :div, class: "resource-errors", data: { resource_id: resource.id }  do %>
    <h2><%= t('.header', count: resource.errors.count) %></h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="col-6 alert <%= class_message(key) %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_flash_html.erb
<% flash.each do |key, message| %>
	<%= content_tag :p, message, class: "flash #{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<footer lass="footer text-muted">
    <div class='m-3'>
      <hr>
      <p><%= t('footer.author', year: current_year) %></p>
      <p><%= t('footer.about') %></p>
      <div>
        <%= github_url('YaponEran','testGuru') %>
        <img src="https://pbs.twimg.com/media/De1g5bsXcAI0xEg.png:large" height='30px'>
      </div>
      <p>
        <%= link_to t('footer.thinknetica'), 'https://thinknetica.com', target: '_blank'%>
      </p>
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light bg-light p-3">
  <% if current_user&.admin? %>
    <%= link_to t('admin.nav.header'), admin_tests_path, class: "navbar-brand btn btn-outline-primary" %>
  <% end %>

    <%= link_to 'Test-Guru', root_path, class: "navbar-brand btn btn-outline-secondary" %>

  <span class="navbar-text">
    <% if user_signed_in? %>
    <%= t('header.welcome') %>, <b><%= current_user.email %></b> |
    <%= link_to t('header.logout'), destroy_user_session_path, method: :delete %>
    <%= link_to 'Your badge',  badges_path %>
    <% else %>
      <%= link_to t('.login'), new_user_session_path %> |
      <%= link_to t('.register'), new_user_registration_path %>
    <% end %> 
  </span>
</nav>